# Model configuration
model:
  name: resnet18  # Options: mobilenetv2, resnet18, densenet121, custom_cnn
  pretrained: false
  num_classes: 100

# Activation function configuration
activation:
  name: relu  # Options: relu, leaky_relu, elu, tanh, gelu, swish, trainable_swish
  leaky_relu_negative_slope: 0.01
  elu_alpha: 1.0
  swish_beta: 1.0
  train_swish_beta: false

# Optimizer configuration
optimizer:
  name: sgd
  lr: 0.05  # Initial learning rate for ImageNet
  momentum: 0.9
  weight_decay: 1e-4  # Weight decay for ImageNet
  nesterov: true  # Enable Nesterov momentum

# Learning rate scheduler configuration
scheduler:
  name: cosine
  warmup_epochs: 5  # Add warmup period
  warmup_start_lr: 0.01  # Start with lower learning rate
  T_max: 90  # 90 epochs for ImageNet
  eta_min: 0.0

# Data configuration
data:
  data_dir: ${oc.env:PWD}/data/imagenet-100  # Use absolute path
  batch_size: 256  # Batch size for ImageNet
  num_workers: 8  # Increased for ImageNet
  image_size: 224
  # ImageNet-specific augmentations
  augmentations:
    resize_size: 256  # Resize to 256 first
    crop_size: 224    # Then random crop to 224
    hflip_prob: 0.5
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Training configuration
training:
  max_epochs: 90  # 90 epochs for ImageNet
  accelerator: "cpu"  # Force CPU usage since CUDA is not available
  devices: 1  # Use single CPU
  precision: 32
  seed: 42
  log_every_n_steps: 50
  gradient_clip_val: null
  # Experiment tracking
  track_convergence: true
  convergence_threshold: 0.95
  track_gpu_memory: false  # Disable GPU memory tracking since we're using CPU
  track_gradients: true  # Track gradient statistics
  track_activations: true  # Track activation statistics
  num_trials: 5  # Number of trials for each configuration
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

# Evaluation metrics
metrics:
  track_top5: true  # Track Top-5 accuracy for ImageNet
  gradient_histogram_bins: 50
  activation_stats_freq: 100  # Log activation stats every N batches
  profile_memory: true
  profile_time: true

# Experiment configuration
experiment_name: ${model.name}-${activation.name}
log_dir: logs

# Removed wandb configuration 